---
title: "Time Series Project"
author: "Erling F Steen"
date: "2022-11-04"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(R.matlab)
library(depmixS4)
```

```{r}
data <- readMat("Mouse28-140313_BS0150_HMMready.mat")
angdata <- as.vector(data$resampledAwakeHeadAngleData)
# Transpose thet data so that there are 71 columns, one column for each cell, and 15243 rows, one for each time interval.
celldata <- t(data$celldata)
```



```{r}
# Exclude cells that are active less than 100 times overall 
col_idx = which(colSums(celldata)<100)
celldata = celldata[,-col_idx]
```


```{r}
# Reduced to 59 cells
dim(celldata)
```

```{r}
cell_data <- data.frame(celldata)

# Response and list must be on list-form

# Response has to be in a list
res <- list()

# List of families. One for each cell
families <- list()

# Number of columns(cells)
n_cells <- ncol(cell_data)

for (i in 1:n_cells) {
  form <- as.formula(paste(colnames(cell_data)[i], "~ 1",sep=""))
  res[[i]] = form
  families[[i]] = poisson()
}
```

```{r}
# Model with 5 states
model5 <- depmix(response = res, nstates = 5, data= cell_data, family = families)
fit5 <- fit(model5)
summary(fit5)
AIC(model5)
```

## Fit models with more than 5 states

```{r}
# Dette tar tid!
# Model with 10 states
#mod10 <- depmix(response = res, nstates = 10, data = cell_data, family = families)
#fit10 <- fit(mod10)
# Model with 15 states
#mod15 <- depmix(response = res, nstates = 15, data = cell_data, family = families)
#fit15 <- fit(mod15)
```

```{r}
#summary(fit10)
```

### Model selection based on AIC

```{r}
# Model selection based on AIC

AIC(fit5)

# AIC(fit10)

# AIC(fit15)

# AIC(fit20)
```

### Indices of each state

```{r}
# States for all time intervals
states = posterior(fit5)$state
# Indices for which state is 1
numstates <- 5

idx_state1 <- which(states == 1)
idx_state2 <- which(states == 2)
idx_state3 <- which(states == 3)
idx_state4 <- which(states == 4)
idx_state5 <- which(states == 5)
idx_state <- list(idx_state1)

for (i in 2:numstates){
  cur_idx <- which(states == i)
  idx_state <- c(idx_state, list(cur_idx))
}

```

```{r}
statevar <- rep(0,numstates)
for (i in 1:numstates){
  statevar[i] <-var(angdata[idx_state[[i]]], na.rm = TRUE)
}
print(statevar)
max_var_state <- which.max(statevar)
```


```{r}
#Avrege for of  

mean_ang_state = rep(0, numstates)
for (i in 1:numstates){
  mean_ang_state[i] <- mean(angdata[idx_state[[i]]], na.rm = TRUE)
}

print(mean_ang_state)
```


```{r}
unsorted_states <- c(1:numstates)
unsorted_states <- unsorted_states[!unsorted_states == max_var_state]
sorted_states <- max_var_state

for (i in 2:numstates){
  cur_min <- which.min(mean_ang_state[unsorted_states])
  sorted_states <- c(sorted_states, unsorted_states[cur_min])
  unsorted_states <- unsorted_states[-cur_min]
}

print(sorted_states)

```



### Histogram over head direction for each state

```{r}
plot(angdata, main="", type="h", col = gray(.7))
text(angdata, col=6*states-2, labels=states, cex=.9)
```

Difficult to see. Take a random sample of the angle data

```{r}
#  Don´t plot all head angles. Take a random sample. Easier to visualize
s_1 = sample(idx_state1, 100)
s_2 = sample(idx_state2, 100)
s_3 = sample(idx_state3, 100)
s_4 = sample(idx_state4, 100)
s_5 = sample(idx_state5, 100)
s=c(s_1, s_2, s_3, s_4, s_5)
```

```{r}
plot(angdata[s], type = "h", col=gray(.7))
text(angdata[s], col = states[s], labels = states[s], cex=.9)
```

```{r}
ts <- which(angdata != "NaN")
xs <- cos(angdata[ts])*ts
ys <- sin(angdata[ts])*ts


plot(xs,ys, col = states[ts]+1, pch = 20, ylab = "", yaxt = "n", xlab = "", xaxt = "n")
abline(v = 0, h =0)
#text(xs,ys, col = states[ts], labels = states[ts])



```



### Plotting the average head direction of each state

```{r}

## Plot of mean head
mean_ang_state
plot(mean_ang_state, type="h")
```


```{r}

transmatrix <- matrix(nrow = 5,ncol = 5)
for (i in 1:5){
  transmatrix[i,]<- fit5@transition[[i]]@parameters$coefficients
}

transmatrix
heatmap(transmatrix[sorted_states,sorted_states], Colv = NA, Rowv = NA, revC = TRUE)


```

